plugins {
    id "org.jetbrains.kotlin.jvm"
}

configurations {
    implementation.extendsFrom(providedCompile)
}

dependencies {
    providedCompile project(path: ':biz.ganttproject.app.libs', configuration: 'exported')
    providedCompile project(path: ':biz.ganttproject.core')
    providedCompile project(path: ':ganttproject')
    implementation group: 'com.itextpdf', name: 'itextpdf', version: '5.+'
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.+'
    testImplementation 'org.junit.platform:junit-platform-launcher:6.1.3'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.13.2'
}


task copyPlugin(dependsOn: jar) {
    install(copyPlugin, jar, project)
}
